id: 51f48c3e-0a90-48fb-9725-41fcdeb5a39f
type: web-application
interactions:
- targetId: 376b04b4-8805-4149-b6cd-d57db170985a
  type: gateway
  level: container
annotations:
- namespace: c4modeler
  name: position
  value:
    578a6b4a-e6d7-4da2-a34b-5fd517568e68:
      x: 435.5896302250804
      y: 124.2154379596281
- namespace: c4modeler
  name: boundary
  value:
    x: 140
    y: 375.5
    width: 280
    height: 751
prefix: app
author: CodeArchitects
target: angular@19
architecture: single-page-application
strict: false
name: NewWebApplication
description: Description for NewWebApplication
children:
- id: 621c53e6-ceaf-4574-aec9-26f6ce5bf808
  type: application
- id: c3e96de6-a99b-45ff-86da-42e9436fb3e0
  type: domain
- id: 3b90e3c1-61cd-4054-9293-ad4effda6d0d
  type: scenario
